export interface WorldCurrency {
  code: string; // ISO 4217 code e.g. "INR", "USD"
  name: string; // Currency name e.g. "Indian Rupee"
  symbol: string; // Symbol e.g. "₹", "$"
  country: string; // Primary country or region e.g. "India"
  countryCode: string; // ISO 3166-1 alpha-2 e.g. "IN"
  flag: string; // Country flag emoji e.g. "🇮🇳"
  region: "Asia" | "Americas" | "Europe" | "Middle East" | "Africa" | "Oceania";
  symbolNative?: string; // Native symbol
  decimalDigits?: number;
}

export const WORLD_CURRENCIES: WorldCurrency[] = [
  // --- ASIA ---
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    symbolNative: "₹",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    symbolNative: "￥",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    region: "Asia",
    decimalDigits: 0,
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    symbolNative: "¥",
    country: "China",
    countryCode: "CN",
    flag: "🇨🇳",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    symbolNative: "$",
    country: "Singapore",
    countryCode: "SG",
    flag: "🇸🇬",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    symbolNative: "$",
    country: "Hong Kong",
    countryCode: "HK",
    flag: "🇭🇰",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    symbolNative: "₩",
    country: "South Korea",
    countryCode: "KR",
    flag: "🇰🇷",
    region: "Asia",
    decimalDigits: 0,
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    symbolNative: "Rp",
    country: "Indonesia",
    countryCode: "ID",
    flag: "🇮🇩",
    region: "Asia",
    decimalDigits: 0,
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    symbolNative: "RM",
    country: "Malaysia",
    countryCode: "MY",
    flag: "🇲🇾",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    symbolNative: "฿",
    country: "Thailand",
    countryCode: "TH",
    flag: "🇹🇭",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    symbolNative: "₱",
    country: "Philippines",
    countryCode: "PH",
    flag: "🇵🇭",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    symbol: "₫",
    symbolNative: "₫",
    country: "Vietnam",
    countryCode: "VN",
    flag: "🇻🇳",
    region: "Asia",
    decimalDigits: 0,
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    symbolNative: "৳",
    country: "Bangladesh",
    countryCode: "BD",
    flag: "🇧🇩",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    symbol: "₨",
    symbolNative: "₨",
    country: "Pakistan",
    countryCode: "PK",
    flag: "🇵🇰",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    symbol: "Rs",
    symbolNative: "රු",
    country: "Sri Lanka",
    countryCode: "LK",
    flag: "🇱🇰",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    symbol: "रू",
    symbolNative: "रू",
    country: "Nepal",
    countryCode: "NP",
    flag: "🇳🇵",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    symbol: "NT$",
    symbolNative: "NT$",
    country: "Taiwan",
    countryCode: "TW",
    flag: "🇹🇼",
    region: "Asia",
    decimalDigits: 2,
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    symbol: "₸",
    symbolNative: "₸",
    country: "Kazakhstan",
    countryCode: "KZ",
    flag: "🇰🇿",
    region: "Asia",
    decimalDigits: 2,
  },

  // --- AMERICAS ---
  {
    code: "USD",
    name: "United States Dollar",
    symbol: "$",
    symbolNative: "$",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    region: "Americas",
    decimalDigits: 2,
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "CA$",
    symbolNative: "$",
    country: "Canada",
    countryCode: "CA",
    flag: "🇨🇦",
    region: "Americas",
    decimalDigits: 2,
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    symbolNative: "R$",
    country: "Brazil",
    countryCode: "BR",
    flag: "🇧🇷",
    region: "Americas",
    decimalDigits: 2,
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    symbol: "MX$",
    symbolNative: "$",
    country: "Mexico",
    countryCode: "MX",
    flag: "🇲🇽",
    region: "Americas",
    decimalDigits: 2,
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    symbol: "ARS$",
    symbolNative: "$",
    country: "Argentina",
    countryCode: "AR",
    flag: "🇦🇷",
    region: "Americas",
    decimalDigits: 2,
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    symbol: "CLP$",
    symbolNative: "$",
    country: "Chile",
    countryCode: "CL",
    flag: "🇨🇱",
    region: "Americas",
    decimalDigits: 0,
  },
  {
    code: "COP",
    name: "Colombian Peso",
    symbol: "COL$",
    symbolNative: "$",
    country: "Colombia",
    countryCode: "CO",
    flag: "🇨🇴",
    region: "Americas",
    decimalDigits: 0,
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    symbolNative: "S/",
    country: "Peru",
    countryCode: "PE",
    flag: "🇵🇪",
    region: "Americas",
    decimalDigits: 2,
  },

  // --- EUROPE ---
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    symbolNative: "€",
    country: "European Union (Germany, France, Italy, Spain)",
    countryCode: "EU",
    flag: "🇪🇺",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    symbolNative: "£",
    country: "United Kingdom",
    countryCode: "GB",
    flag: "🇬🇧",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    symbolNative: "CHF",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    symbolNative: "kr",
    country: "Sweden",
    countryCode: "SE",
    flag: "🇸🇪",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    symbolNative: "kr",
    country: "Norway",
    countryCode: "NO",
    flag: "🇳🇴",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    symbolNative: "kr",
    country: "Denmark",
    countryCode: "DK",
    flag: "🇩🇰",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    symbolNative: "zł",
    country: "Poland",
    countryCode: "PL",
    flag: "🇵🇱",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    symbolNative: "Kč",
    country: "Czech Republic",
    countryCode: "CZ",
    flag: "🇨🇿",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    symbol: "Ft",
    symbolNative: "Ft",
    country: "Hungary",
    countryCode: "HU",
    flag: "🇭🇺",
    region: "Europe",
    decimalDigits: 0,
  },
  {
    code: "RON",
    name: "Romanian Leu",
    symbol: "lei",
    symbolNative: "lei",
    country: "Romania",
    countryCode: "RO",
    flag: "🇷🇴",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    symbolNative: "₺",
    country: "Turkey",
    countryCode: "TR",
    flag: "🇹🇷",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    symbol: "₴",
    symbolNative: "грн",
    country: "Ukraine",
    countryCode: "UA",
    flag: "🇺🇦",
    region: "Europe",
    decimalDigits: 2,
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    symbolNative: "₽",
    country: "Russia",
    countryCode: "RU",
    flag: "🇷🇺",
    region: "Europe",
    decimalDigits: 2,
  },

  // --- MIDDLE EAST ---
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "AED",
    symbolNative: "د.إ",
    country: "United Arab Emirates",
    countryCode: "AE",
    flag: "🇦🇪",
    region: "Middle East",
    decimalDigits: 2,
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "SAR",
    symbolNative: "﷼",
    country: "Saudi Arabia",
    countryCode: "SA",
    flag: "🇸🇦",
    region: "Middle East",
    decimalDigits: 2,
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    symbol: "QAR",
    symbolNative: "ر.ق",
    country: "Qatar",
    countryCode: "QA",
    flag: "🇶🇦",
    region: "Middle East",
    decimalDigits: 2,
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "KWD",
    symbolNative: "د.ك",
    country: "Kuwait",
    countryCode: "KW",
    flag: "🇰🇼",
    region: "Middle East",
    decimalDigits: 3,
  },
  {
    code: "OMR",
    name: "Omani Rial",
    symbol: "OMR",
    symbolNative: "ر.ع.",
    country: "Oman",
    countryCode: "OM",
    flag: "🇴🇲",
    region: "Middle East",
    decimalDigits: 3,
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    symbol: "BHD",
    symbolNative: "د.ب.",
    country: "Bahrain",
    countryCode: "BH",
    flag: "🇧🇭",
    region: "Middle East",
    decimalDigits: 3,
  },
  {
    code: "ILS",
    name: "Israeli Shekel",
    symbol: "₪",
    symbolNative: "₪",
    country: "Israel",
    countryCode: "IL",
    flag: "🇮🇱",
    region: "Middle East",
    decimalDigits: 2,
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    symbol: "JOD",
    symbolNative: "د.أ",
    country: "Jordan",
    countryCode: "JO",
    flag: "🇯🇴",
    region: "Middle East",
    decimalDigits: 3,
  },

  // --- AFRICA ---
  {
    code: "ZAR",
    name: "South African Rand",
    symbol: "R",
    symbolNative: "R",
    country: "South Africa",
    countryCode: "ZA",
    flag: "🇿🇦",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    symbol: "E£",
    symbolNative: "ج.م",
    country: "Egypt",
    countryCode: "EG",
    flag: "🇪🇬",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    symbol: "₦",
    symbolNative: "₦",
    country: "Nigeria",
    countryCode: "NG",
    flag: "🇳🇬",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    symbol: "KSh",
    symbolNative: "KSh",
    country: "Kenya",
    countryCode: "KE",
    flag: "🇰🇪",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    symbol: "GH₵",
    symbolNative: "GH₵",
    country: "Ghana",
    countryCode: "GH",
    flag: "🇬🇭",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    symbol: "MAD",
    symbolNative: "د.م.",
    country: "Morocco",
    countryCode: "MA",
    flag: "🇲🇦",
    region: "Africa",
    decimalDigits: 2,
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    symbol: "₨",
    symbolNative: "₨",
    country: "Mauritius",
    countryCode: "MU",
    flag: "🇲🇺",
    region: "Africa",
    decimalDigits: 2,
  },

  // --- OCEANIA ---
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    symbolNative: "$",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    region: "Oceania",
    decimalDigits: 2,
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    symbolNative: "$",
    country: "New Zealand",
    countryCode: "NZ",
    flag: "🇳🇿",
    region: "Oceania",
    decimalDigits: 2,
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    symbol: "FJ$",
    symbolNative: "$",
    country: "Fiji",
    countryCode: "FJ",
    flag: "🇫🇯",
    region: "Oceania",
    decimalDigits: 2,
  },
];

/**
 * Formats a sample monetary value using the currency's locale convention
 * e.g. INR -> ₹1,00,000, USD -> $10,000
 */
export function formatCurrencySample(code: string, amount: number = 10000): string {
  const locale = code.toUpperCase() === "INR" ? "en-IN" : "en-US";
  try {
    return new Intl.NumberFormat(locale, {
      style: "currency",
      currency: code,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    const item = WORLD_CURRENCIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
    return `${item?.symbol || code} ${amount.toLocaleString()}`;
  }
}
