export interface CountryTimezone {
  value: string;
  country: string;
  countryCode: string;
  flag: string;
  label: string;
  cities: string;
  offset: string;
  region: "Asia" | "Americas" | "Europe" | "Middle East" | "Africa" | "Oceania";
}

export const COUNTRY_TIMEZONES: CountryTimezone[] = [
  // --- ASIA ---
  {
    value: "Asia/Kolkata",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    label: "Indian Standard Time (IST)",
    cities: "New Delhi, Mumbai, Bengaluru, Kolkata, Chennai, Hyderabad",
    offset: "UTC+05:30",
    region: "Asia",
  },
  {
    value: "Asia/Singapore",
    country: "Singapore",
    countryCode: "SG",
    flag: "🇸🇬",
    label: "Singapore Time (SGT)",
    cities: "Singapore",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Tokyo",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    label: "Japan Standard Time (JST)",
    cities: "Tokyo, Osaka, Kyoto, Yokohama",
    offset: "UTC+09:00",
    region: "Asia",
  },
  {
    value: "Asia/Shanghai",
    country: "China",
    countryCode: "CN",
    flag: "🇨🇳",
    label: "China Standard Time (CST)",
    cities: "Beijing, Shanghai, Shenzhen, Guangzhou",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Hong_Kong",
    country: "Hong Kong",
    countryCode: "HK",
    flag: "🇭🇰",
    label: "Hong Kong Time (HKT)",
    cities: "Hong Kong",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Seoul",
    country: "South Korea",
    countryCode: "KR",
    flag: "🇰🇷",
    label: "Korea Standard Time (KST)",
    cities: "Seoul, Busan, Incheon",
    offset: "UTC+09:00",
    region: "Asia",
  },
  {
    value: "Asia/Jakarta",
    country: "Indonesia",
    countryCode: "ID",
    flag: "🇮🇩",
    label: "Western Indonesia Time (WIB)",
    cities: "Jakarta, Surabaya, Bandung",
    offset: "UTC+07:00",
    region: "Asia",
  },
  {
    value: "Asia/Kuala_Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    flag: "🇲🇾",
    label: "Malaysia Time (MYT)",
    cities: "Kuala Lumpur, George Town, Johor Bahru",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Bangkok",
    country: "Thailand",
    countryCode: "TH",
    flag: "🇹🇭",
    label: "Indochina Time (ICT)",
    cities: "Bangkok, Chiang Mai, Phuket",
    offset: "UTC+07:00",
    region: "Asia",
  },
  {
    value: "Asia/Ho_Chi_Minh",
    country: "Vietnam",
    countryCode: "VN",
    flag: "🇻🇳",
    label: "Indochina Time (ICT)",
    cities: "Ho Chi Minh City, Hanoi, Da Nang",
    offset: "UTC+07:00",
    region: "Asia",
  },
  {
    value: "Asia/Manila",
    country: "Philippines",
    countryCode: "PH",
    flag: "🇵🇭",
    label: "Philippine Standard Time (PST)",
    cities: "Manila, Quezon City, Cebu",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Taipei",
    country: "Taiwan",
    countryCode: "TW",
    flag: "🇹🇼",
    label: "Taipei Standard Time (CST)",
    cities: "Taipei, Kaohsiung, Taichung",
    offset: "UTC+08:00",
    region: "Asia",
  },
  {
    value: "Asia/Karachi",
    country: "Pakistan",
    countryCode: "PK",
    flag: "🇵🇰",
    label: "Pakistan Standard Time (PKT)",
    cities: "Karachi, Lahore, Islamabad",
    offset: "UTC+05:00",
    region: "Asia",
  },
  {
    value: "Asia/Dhaka",
    country: "Bangladesh",
    countryCode: "BD",
    flag: "🇧🇩",
    label: "Bangladesh Standard Time (BST)",
    cities: "Dhaka, Chittagong",
    offset: "UTC+06:00",
    region: "Asia",
  },
  {
    value: "Asia/Kathmandu",
    country: "Nepal",
    countryCode: "NP",
    flag: "🇳🇵",
    label: "Nepal Time (NPT)",
    cities: "Kathmandu, Pokhara",
    offset: "UTC+05:45",
    region: "Asia",
  },
  {
    value: "Asia/Colombo",
    country: "Sri Lanka",
    countryCode: "LK",
    flag: "🇱🇰",
    label: "Sri Lanka Standard Time (SLST)",
    cities: "Colombo, Kandy",
    offset: "UTC+05:30",
    region: "Asia",
  },

  // --- MIDDLE EAST ---
  {
    value: "Asia/Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    flag: "🇦🇪",
    label: "Gulf Standard Time (GST)",
    cities: "Dubai, Abu Dhabi, Sharjah",
    offset: "UTC+04:00",
    region: "Middle East",
  },
  {
    value: "Asia/Riyadh",
    country: "Saudi Arabia",
    countryCode: "SA",
    flag: "🇸🇦",
    label: "Arabian Standard Time (AST)",
    cities: "Riyadh, Jeddah, Mecca",
    offset: "UTC+03:00",
    region: "Middle East",
  },
  {
    value: "Asia/Qatar",
    country: "Qatar",
    countryCode: "QA",
    flag: "🇶🇦",
    label: "Arabian Standard Time (AST)",
    cities: "Doha",
    offset: "UTC+03:00",
    region: "Middle East",
  },
  {
    value: "Asia/Kuwait",
    country: "Kuwait",
    countryCode: "KW",
    flag: "🇰🇼",
    label: "Arabian Standard Time (AST)",
    cities: "Kuwait City",
    offset: "UTC+03:00",
    region: "Middle East",
  },
  {
    value: "Europe/Istanbul",
    country: "Turkey",
    countryCode: "TR",
    flag: "🇹🇷",
    label: "Turkey Time (TRT)",
    cities: "Istanbul, Ankara, Izmir",
    offset: "UTC+03:00",
    region: "Middle East",
  },
  {
    value: "Asia/Jerusalem",
    country: "Israel",
    countryCode: "IL",
    flag: "🇮🇱",
    label: "Israel Standard Time (IST)",
    cities: "Jerusalem, Tel Aviv",
    offset: "UTC+02:00",
    region: "Middle East",
  },

  // --- EUROPE ---
  {
    value: "Europe/London",
    country: "United Kingdom",
    countryCode: "GB",
    flag: "🇬🇧",
    label: "Greenwich Mean Time (GMT / BST)",
    cities: "London, Manchester, Edinburgh, Birmingham",
    offset: "UTC+00:00",
    region: "Europe",
  },
  {
    value: "Europe/Dublin",
    country: "Ireland",
    countryCode: "IE",
    flag: "🇮🇪",
    label: "Irish Standard Time (IST)",
    cities: "Dublin, Cork, Galway",
    offset: "UTC+00:00",
    region: "Europe",
  },
  {
    value: "Europe/Berlin",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    label: "Central European Time (CET)",
    cities: "Berlin, Frankfurt, Munich, Hamburg",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Paris",
    country: "France",
    countryCode: "FR",
    flag: "🇫🇷",
    label: "Central European Time (CET)",
    cities: "Paris, Lyon, Marseille",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    flag: "🇳🇱",
    label: "Central European Time (CET)",
    cities: "Amsterdam, Rotterdam, The Hague",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Zurich",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    label: "Central European Time (CET)",
    cities: "Zurich, Geneva, Bern",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Rome",
    country: "Italy",
    countryCode: "IT",
    flag: "🇮🇹",
    label: "Central European Time (CET)",
    cities: "Rome, Milan, Naples",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Madrid",
    country: "Spain",
    countryCode: "ES",
    flag: "🇪🇸",
    label: "Central European Time (CET)",
    cities: "Madrid, Barcelona, Valencia",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Lisbon",
    country: "Portugal",
    countryCode: "PT",
    flag: "🇵🇹",
    label: "Western European Time (WET)",
    cities: "Lisbon, Porto",
    offset: "UTC+00:00",
    region: "Europe",
  },
  {
    value: "Europe/Stockholm",
    country: "Sweden",
    countryCode: "SE",
    flag: "🇸🇪",
    label: "Central European Time (CET)",
    cities: "Stockholm, Gothenburg",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Oslo",
    country: "Norway",
    countryCode: "NO",
    flag: "🇳🇴",
    label: "Central European Time (CET)",
    cities: "Oslo, Bergen",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    flag: "🇩🇰",
    label: "Central European Time (CET)",
    cities: "Copenhagen, Aarhus",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Helsinki",
    country: "Finland",
    countryCode: "FI",
    flag: "🇫🇮",
    label: "Eastern European Time (EET)",
    cities: "Helsinki, Espoo",
    offset: "UTC+02:00",
    region: "Europe",
  },
  {
    value: "Europe/Warsaw",
    country: "Poland",
    countryCode: "PL",
    flag: "🇵🇱",
    label: "Central European Time (CET)",
    cities: "Warsaw, Krakow",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Vienna",
    country: "Austria",
    countryCode: "AT",
    flag: "🇦🇹",
    label: "Central European Time (CET)",
    cities: "Vienna, Salzburg",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Brussels",
    country: "Belgium",
    countryCode: "BE",
    flag: "🇧🇪",
    label: "Central European Time (CET)",
    cities: "Brussels, Antwerp",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Athens",
    country: "Greece",
    countryCode: "GR",
    flag: "🇬🇷",
    label: "Eastern European Time (EET)",
    cities: "Athens, Thessaloniki",
    offset: "UTC+02:00",
    region: "Europe",
  },
  {
    value: "Europe/Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    flag: "🇨🇿",
    label: "Central European Time (CET)",
    cities: "Prague, Brno",
    offset: "UTC+01:00",
    region: "Europe",
  },
  {
    value: "Europe/Moscow",
    country: "Russia",
    countryCode: "RU",
    flag: "🇷🇺",
    label: "Moscow Standard Time (MSK)",
    cities: "Moscow, Saint Petersburg",
    offset: "UTC+03:00",
    region: "Europe",
  },

  // --- AMERICAS ---
  {
    value: "America/New_York",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Eastern Time (ET)",
    cities: "New York, Washington D.C., Boston, Atlanta, Miami",
    offset: "UTC-05:00",
    region: "Americas",
  },
  {
    value: "America/Chicago",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Central Time (CT)",
    cities: "Chicago, Dallas, Houston, Austin, Minneapolis",
    offset: "UTC-06:00",
    region: "Americas",
  },
  {
    value: "America/Denver",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Mountain Time (MT)",
    cities: "Denver, Phoenix, Salt Lake City",
    offset: "UTC-07:00",
    region: "Americas",
  },
  {
    value: "America/Los_Angeles",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Pacific Time (PT)",
    cities: "Los Angeles, San Francisco, Seattle, Silicon Valley",
    offset: "UTC-08:00",
    region: "Americas",
  },
  {
    value: "America/Anchorage",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Alaska Time (AKT)",
    cities: "Anchorage, Fairbanks",
    offset: "UTC-09:00",
    region: "Americas",
  },
  {
    value: "Pacific/Honolulu",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    label: "Hawaii-Aleutian Time (HST)",
    cities: "Honolulu",
    offset: "UTC-10:00",
    region: "Americas",
  },
  {
    value: "America/Toronto",
    country: "Canada",
    countryCode: "CA",
    flag: "🇨🇦",
    label: "Eastern Time (Canada)",
    cities: "Toronto, Ottawa, Montreal",
    offset: "UTC-05:00",
    region: "Americas",
  },
  {
    value: "America/Vancouver",
    country: "Canada",
    countryCode: "CA",
    flag: "🇨🇦",
    label: "Pacific Time (Canada)",
    cities: "Vancouver, Victoria",
    offset: "UTC-08:00",
    region: "Americas",
  },
  {
    value: "America/Sao_Paulo",
    country: "Brazil",
    countryCode: "BR",
    flag: "🇧🇷",
    label: "Brasília Time (BRT)",
    cities: "São Paulo, Rio de Janeiro, Brasília",
    offset: "UTC-03:00",
    region: "Americas",
  },
  {
    value: "America/Mexico_City",
    country: "Mexico",
    countryCode: "MX",
    flag: "🇲🇽",
    label: "Central Time (Mexico)",
    cities: "Mexico City, Guadalajara, Monterrey",
    offset: "UTC-06:00",
    region: "Americas",
  },
  {
    value: "America/Argentina/Buenos_Aires",
    country: "Argentina",
    countryCode: "AR",
    flag: "🇦🇷",
    label: "Argentina Time (ART)",
    cities: "Buenos Aires, Cordoba",
    offset: "UTC-03:00",
    region: "Americas",
  },
  {
    value: "America/Bogota",
    country: "Colombia",
    countryCode: "CO",
    flag: "🇨🇴",
    label: "Colombia Time (COT)",
    cities: "Bogota, Medellin",
    offset: "UTC-05:00",
    region: "Americas",
  },
  {
    value: "America/Santiago",
    country: "Chile",
    countryCode: "CL",
    flag: "🇨🇱",
    label: "Chile Standard Time (CLT)",
    cities: "Santiago, Valparaiso",
    offset: "UTC-04:00",
    region: "Americas",
  },
  {
    value: "America/Lima",
    country: "Peru",
    countryCode: "PE",
    flag: "🇵🇪",
    label: "Peru Time (PET)",
    cities: "Lima, Arequipa",
    offset: "UTC-05:00",
    region: "Americas",
  },

  // --- OCEANIA & PACIFIC ---
  {
    value: "Australia/Sydney",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    label: "Australian Eastern Time (AEST / AEDT)",
    cities: "Sydney, Canberra",
    offset: "UTC+10:00",
    region: "Oceania",
  },
  {
    value: "Australia/Melbourne",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    label: "Australian Eastern Time (Melbourne)",
    cities: "Melbourne",
    offset: "UTC+10:00",
    region: "Oceania",
  },
  {
    value: "Australia/Brisbane",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    label: "Australian Eastern Standard Time (AEST)",
    cities: "Brisbane, Gold Coast",
    offset: "UTC+10:00",
    region: "Oceania",
  },
  {
    value: "Australia/Perth",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    label: "Australian Western Standard Time (AWST)",
    cities: "Perth",
    offset: "UTC+08:00",
    region: "Oceania",
  },
  {
    value: "Pacific/Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    flag: "🇳🇿",
    label: "New Zealand Standard Time (NZST)",
    cities: "Auckland, Wellington, Christchurch",
    offset: "UTC+12:00",
    region: "Oceania",
  },

  // --- AFRICA ---
  {
    value: "Africa/Johannesburg",
    country: "South Africa",
    countryCode: "ZA",
    flag: "🇿🇦",
    label: "South Africa Standard Time (SAST)",
    cities: "Johannesburg, Cape Town, Pretoria",
    offset: "UTC+02:00",
    region: "Africa",
  },
  {
    value: "Africa/Cairo",
    country: "Egypt",
    countryCode: "EG",
    flag: "🇪🇬",
    label: "Eastern European Time (EET)",
    cities: "Cairo, Alexandria",
    offset: "UTC+02:00",
    region: "Africa",
  },
  {
    value: "Africa/Lagos",
    country: "Nigeria",
    countryCode: "NG",
    flag: "🇳🇬",
    label: "West Africa Time (WAT)",
    cities: "Lagos, Abuja",
    offset: "UTC+01:00",
    region: "Africa",
  },
  {
    value: "Africa/Nairobi",
    country: "Kenya",
    countryCode: "KE",
    flag: "🇰🇪",
    label: "East Africa Time (EAT)",
    cities: "Nairobi, Mombasa",
    offset: "UTC+03:00",
    region: "Africa",
  },
  {
    value: "Africa/Casablanca",
    country: "Morocco",
    countryCode: "MA",
    flag: "🇲🇦",
    label: "Western European Time (WET)",
    cities: "Casablanca, Rabat",
    offset: "UTC+01:00",
    region: "Africa",
  },
];

/**
 * Returns current local time in given timezone, e.g. "11:05 PM"
 */
export function getLiveTimeInTimezone(timeZone: string, date: Date = new Date()): string {
  try {
    return new Intl.DateTimeFormat("en-US", {
      timeZone,
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    }).format(date);
  } catch {
    return "--:--";
  }
}

/**
 * Returns calculated current dynamic UTC offset string, e.g. "UTC+05:30"
 */
export function getLiveOffsetInTimezone(timeZone: string, date: Date = new Date()): string {
  try {
    const formatter = new Intl.DateTimeFormat("en-US", {
      timeZone,
      timeZoneName: "shortOffset",
    });
    const parts = formatter.formatToParts(date);
    const tzPart = parts.find((p) => p.type === "timeZoneName");
    if (tzPart?.value) {
      // Normalize GMT+5:30 or UTC+5:30 to UTC+05:30
      const val = tzPart.value.replace("GMT", "UTC");
      return val === "UTC" ? "UTC+00:00" : val;
    }
  } catch {
    // fallback
  }
  return "";
}
